name: Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Check out code
      uses: actions/checkout@v2.3.4

    - name: Run tests on linux
      run: go test -v -race -cover -covermode=atomic -coverprofile=cover.txt ./...

    - name: Upload coverage report to codecov.io
      uses: codecov/codecov-action@v1.5.2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./cover.txt
